# .codeclimate.yml
version: "2"
checks:
  # Increase allowed complexity.
  # Because currying isn't complex
  method-complexity:
    config:
      threshold: 6
  # Disable checks for similar code.
  # Because this creates too many false positives.
  similar-code:
    enabled: false
  # Increase the number of lines allowed for a method.
  # Because this is more reasonable for Javascript.
  method-lines:
    config:
      threshold: 50
exclude_patterns:
  - "**/__tests__/*"
  - "**/coverage/*"
  - "**/*.spec.js/*"
  - "**/*.spec.jsx/*"
  - "**/*.spec.ts/*"
  - "**/*.spec.tsx/*"
  - "**/vendor/*"
  - "**/node_modules/*"
