version: "3.7"
services:
  db:
    container_name: "user_db"
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
